apiVersion: v1
kind: ImageStream
metadata:
  labels:
    role: jenkins-slave
  name: go
spec:
  tags:
  - from:
      kind: DockerImage
      name: docker.io/outtherelabs/jenkins-slave-golang:latest
    name: latest

